--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-25-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QNA
--------------------------------------------------------

  CREATE TABLE "TEST7"."QNA" 
   (	"QNA_IDX" NUMBER(20,0), 
	"QNA_TITLE" VARCHAR2(100 BYTE), 
	"QNA_CONTENT" VARCHAR2(1000 BYTE), 
	"QNA_ID" VARCHAR2(20 BYTE), 
	"QNA_RESDATE" DATE DEFAULT current_timestamp, 
	"LEV" NUMBER(5,0), 
	"PARNO" NUMBER(20,0), 
	"REPLY_CNT" NUMBER(5,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TEST7.QNA
SET DEFINE OFF;
Insert into TEST7.QNA (QNA_IDX,QNA_TITLE,QNA_CONTENT,QNA_ID,QNA_RESDATE,LEV,PARNO,REPLY_CNT) values (1,'질문글1','질문글1','user2',to_date('23/07/25','RR/MM/DD'),1,1,2);
Insert into TEST7.QNA (QNA_IDX,QNA_TITLE,QNA_CONTENT,QNA_ID,QNA_RESDATE,LEV,PARNO,REPLY_CNT) values (2,'질문글1 의 답변글1','질문글1 의 답변글1','user3',to_date('23/07/25','RR/MM/DD'),2,1,0);
Insert into TEST7.QNA (QNA_IDX,QNA_TITLE,QNA_CONTENT,QNA_ID,QNA_RESDATE,LEV,PARNO,REPLY_CNT) values (6,'질문글2 의 답변글1','질문글2 의 답변글1','user2',to_date('23/07/25','RR/MM/DD'),2,4,0);
Insert into TEST7.QNA (QNA_IDX,QNA_TITLE,QNA_CONTENT,QNA_ID,QNA_RESDATE,LEV,PARNO,REPLY_CNT) values (4,'질문글2','질문글2','user3',to_date('23/07/25','RR/MM/DD'),1,4,2);
Insert into TEST7.QNA (QNA_IDX,QNA_TITLE,QNA_CONTENT,QNA_ID,QNA_RESDATE,LEV,PARNO,REPLY_CNT) values (5,'질문글1 의 답변글3','질문글1 의 답변글3','user3',to_date('23/07/25','RR/MM/DD'),2,1,0);
Insert into TEST7.QNA (QNA_IDX,QNA_TITLE,QNA_CONTENT,QNA_ID,QNA_RESDATE,LEV,PARNO,REPLY_CNT) values (7,'질문글2 의 답변글2','질문글2 의 답변글2','user2',to_date('23/07/25','RR/MM/DD'),2,4,0);
--------------------------------------------------------
--  DDL for Index SYS_C007663
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST7"."SYS_C007663" ON "TEST7"."QNA" ("QNA_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "TEST7"."QNA" ADD PRIMARY KEY ("QNA_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST7"."QNA" MODIFY ("QNA_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "TEST7"."QNA" MODIFY ("QNA_TITLE" NOT NULL ENABLE);
  ALTER TABLE "TEST7"."QNA" MODIFY ("QNA_IDX" NOT NULL ENABLE);
